"""empty message

Revision ID: eb6675b0abaa
Revises: 8779acf8ebc9
Create Date: 2018-07-10 11:08:50.886034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb6675b0abaa'
down_revision = '8779acf8ebc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('icon_path', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'icon_path')
    # ### end Alembic commands ###
